### PR TITLE
revive timezone support

### PR DESCRIPTION
**Pull request by frispete**
Hi Daniel,

based on Ivan Mirićs initial timezone support, I ported it to the current
schedule module.

The hard part doing it in an optional fashion isn't done yet.

I don't have a brilliant idea, how to separate the two in an useful way. The usual subclass approach would not get rid of the additional dependency for the schedule package, while refactoring the two classes into _dependant_ projects is complete overkill. I'm not willing to do the third way of forking your project.

The forth approach: just merge is my favorite still. The additional complexity of dealing with timezones isn't exactly nice, but is a recurring problem, when it comes to scheduling. OTOH, allowing both naive and offset aware datetimes isn't appealing conceptually as well.

[Review on Reviewable](https://reviewable.io/reviews/dbader/schedule/75)

### CODE REVIEW

**Comment by frispete** [comment]
Why does travis not install the necessary requirements, as noted in setup.py?

**Comment by dbader** [comment]
> Why does travis not install the necessary requirements, as noted in setup.py?

It should do it now that we're just running Tox on CI (#79).

**Comment by dbader** [comment]
Thanks for the PR 😃  I can see where timezone support would be useful!

The main thing I'm worried here is that we're shipping our own timezone definitions – Ideally we should pull them in from some other module so that the maintenance burden isn't on us.

Any ideas on how we could accomplish that?

**Comment by frispete** [comment]
Hi Daniel, nice to see you up and alive ;)

Well, the definition, which timezones have which offset, is pretty fixed, isn't it? 
Okay, given the tectonic movement, these offsets might change in a few hundred thousands of years. Not sure, if schedule is still used at that time. Invention of new timezones is probably more frequent, but also not THAT common ;)..

Those are used in order to _not_ deal with the timezones itself, e.g. to support parser of dateutil, which is a pretty common module, if you need to deal with timezones...

I haven't investigated other possibilities, yet, but they will come with a price: another dependency.

**Comment by dbader** [comment]
> Hi Daniel, nice to see you up and alive ;)

Thanks ;)

> Well, the definition, which timezones have which offset, is pretty fixed, isn't it? 

That's what I thought too but it turns out it's more complicated than that :) The Olson tz database changes quite frequently: https://en.wikipedia.org/wiki/Tz_database The main reason seems to be updates in daylight savings time. I'm not looking forward to having to keep up with that as a maintainer :)

The alternative that I'd prefer is that we add an optional argument representing the timezone or the tz offset – instead of passing a human readable identifier (== the string tz abbreviation).

Then people could just use [pytz](http://pytz.sourceforge.net/) or whatever other tz database they'd like to use to lookup the offset – alleviating schedule from the maintenance burden.

This needs to be fleshed out further, but how about something like this:

```python
from pytz import timezone

EST = timezone('US/Eastern')
schedule.every().day.at("10:00", EST)

schedule.every().day.at("10:00", pytz.utc)
```

Does that make sense?

**Comment by frispete** [comment]
On Mittwoch, 9. November 2016 05:50:35 Daniel Bader wrote:
> > Hi Daniel, nice to see you up and alive ;)
> 
> Thanks ;)
> 
> > Well, the definition, which timezones have which offset, is pretty fixed,
> > isn't it?
> That's what I thought too but it turns out it's more complicated than that
> :) The Olson tz database changes quite frequently:
> https://en.wikipedia.org/wiki/Tz_database The main reason seems to be
> updates in daylight savings time. I'm not looking forward to having to keep
> up with that as a maintainer :)

But that's my point. Due to using dateutil, the Olson tz database is used behind the 
scenes. 

The mapping of timezone offsets doesn't change. What's changing on a regular base is, 
when and if some daylight savings time is applied in a certain TZ.

Check the diffs: it's just an offset mapping. An those values don't change that often, as 
these relate to "quite stable" geographic coordinates (e.g. tectonic drift)...
 
> The alternative that I'd prefer is that we add an optional argument
> representing the timezone or the tz offset – instead of passing a human
> readable identifier (== the string tz abbreviation).
> 
> Then people could just use [pytz](http://pytz.sourceforge.net/) or whatever
> other tz database they'd like to use to lookup the offset – alleviating
> schedule from the maintenance burden.
> 
> This needs to be fleshed out further, but how about something like this:
> 
> ```python
> from pytz import timezone
> 
> EST = timezone('US/Eastern')
> schedule.every().day.at("10:00", EST)
> 
> schedule.every().day.at("10:00", pytz.utc)
> ```
>
> Does that make sense?

Sure, the only downside, I see, are schedule events from config files. In my proposed 
scheme, the TZ argument is passed though and will just work. Your scheme places the 
burden on the apps config parser code, that, at some point, will want to use a similar 
mapping.

I'm pretty sure, that the mapping will not change in the next decade, because, even if 
some pacific islands decide to change their timezone assignment, they hopefully will 
choose an existing one from their neighbors in flavor of inventing some new ones, that 
nobody knows. 

Cheers,
Pete

**Comment by dbader** [comment]
Closing this for now, we need to resolve some other TZ issues with schedule first and I think we should go for an implementation that doesn't include a TZ table. Thanks for your PR though!

**Comment by allthetime** [comment]
@dbader the system itself already contains the most complete timezone table, complete with DST oddities that is possible to have, I'm assuming this is what decent existing time libraries use. I just looked through `pendulum` for instance and it doesn't have that data hardcoded anywhere and reads it directly from the system. The only data table they have is converting windows timezone names to  I'm assuming the standard python libs do the same, I haven't verified that though...

anyways, including and maintaining a TZ table here is definitely the wrong idea, but the solution is already available. I imagine you wouldn't want to include pendulum as a dependency though, but some of it's code could be incorporated to accomplish this.

**Pull request closed without merging**
