### PR TITLE
How to pass arguments

### PR DESCRIPTION
**Pull request by anselal**
Code taken from #31

### CODE REVIEW

**Comment by dbader** [comment]
Thanks. This should be an FAQ item and not go directly into the README.

**Comment by dbader** [comment]
@anselal https://schedule.readthedocs.io/en/stable/faq.html

**Comment by SijmenHuizenga** [comment]
Hi there! Documentation about passing arguments to a function has been added to the latest version of the docs and can be found here: https://schedule.readthedocs.io/en/latest/examples.html#pass-arguments-to-a-job

**Comment by anselal** [comment]
that is great !!!

**Pull request closed without merging**
