### PR TITLE
Timezone support

### PR DESCRIPTION
**Pull request by imiric**
Hi,

I added timezone support using python-dateutil. Yes, it's not as minimal as before, but I think the functionality makes up for it. :-) Hope you agree.

Ivan

### CODE REVIEW

**Comment by fphilipe** [comment]
In a project I'm involved with we currently have a ruby setup to trigger tasks periodically that calculate some stats for our customers. We're porting the stats calculation to python and are looking for a replacement for the rubygem [clockwork](https://github.com/tomykaira/clockwork). schedule looks very promising and quite similar to clockwork, except the lack of support for time zones.

Since you were asking about possible use cases, I want to share ours with you. We have certain tasks that run at the beginning of the day/week/month for every customer. Since customers are in a different timezone, we need to trigger those jobs at midnight of their respective time zone. Thus, we have something as follows with clockwork, which supports specifying the time zone optionally through the `tz` option:

```ruby
customers.each do |customer|
  every(1.month, 'stats.monthly', at: '00:00', tz: customer.time_zone)
  # customer.time_zone would be 'Europe/Berlin' for example.
end
```

Let me know whether this is something you could imagine having in schedule. I've also been looking into apscheduler, but this seems to have a simpler interface.

**Comment by kmonsoor** [comment]
just chiming in to add my use case.
I need to run a complex-but-single Python task everyday at **midnight PST**. As my server runs on UTC, I have to translate it before I can "schedule" it. Also, I have to manage the daylight-saving manually.

**Comment by zcking** [comment]
Hi I'm new to schedule, but would love to see this feature included officially. I've dealt a lot with localization using Django and it's django.utils.timezone utility, so localization is something I consider with nearly every project now. 

If it's important to omit external dependencies like python-dateutil I would love to take a stab with my first contribution using the built-in datetime.tzinfo that is available to both Python 2 and 3. Thoughts?

**Comment by jaraco** [comment]
I'd also like support for timezones. I currently maintain [tempora](https://github.com/jaraco/tempora) whose schedule module implements a timezone-aware scheduler. But it has [a bug](https://github.com/jaraco/tempora/issues/5) that it fails to honor the timezone when DST changes. I was hoping this project might be a suitable replacement, but lack of timezone support is a deal-breaker.

In that respect, I reviewed the implementation, and it doesn't appear to have any support for the daylight savings effect in a given timezone; it's fixed to either standard time or daylight time. Do I read that correctly?

In my application, I wish for a user to be able to schedule an event to occur at a particular time of day on the wall clock, meaning for example it happens at 09:00 each day, even when that time may be 25 or 23 hours from the last time (due to DST). I'd be delighted if that consideration could be included in this request.

**Comment by xverges** [comment]
The dependency could be specified as [an extra](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) and use some stub functions that would throw if timezones were used without having the ability to import `dateutil`

**Comment by stefansimik** [comment]
@dbader 
I would also appreciate, if timezones were supported.
It is basic requirement for using this library in international environment,
where everyone has different time.

I would be happy to use this lib - it is so nice, simple and clear,
but timezones are really missing. I believe, such a great library deserves timezone support.

**Comment by Lawouach** [comment]
Hello @dbader,

I'm a little confused. Is the fact this PR closed (unmerged) a signal that timezone will never be part of the package?

**Comment by Juanlu001** [comment]
@Lawouach:

> My requirement for merging this into master is that we make timezone support optional.

https://github.com/dbader/schedule/pull/16#issuecomment-23578667

So, if I understand correctly, if someone comes up with a way to rewrite this PR in a way that timezone support is optional, @dbader would be willing to merge it.

**Comment by thedrow** [comment]
I'm actually in favor of keeping dateutil as a dependency even if I end up not using it.
There's no reason to avoid installing it, isn't it?

**Comment by septatrix** [comment]
I may have some free time this month and could try to rewrite this using pythons native timezone functionality...

**Comment by jaraco** [comment]
For what it's worth, tempora.schedule has turned out to be an effective and timezone-aware implementation. I have little hesitation in recommending it today.

**Comment by qlbnb** [comment]
Alternatively, if I convert desired timezone info to system time, and use it as it is, should I expected potential pitfalls? https://stackoverflow.com/questions/4770297/convert-utc-datetime-string-to-local-datetime

**Pull request closed without merging**
