### PR TITLE
Resolves #470: Add timezone functionality

### LINKED ISSUE #470: New Method to declare timezone: `tz()`
I would like to define the timezone when I would like my scheduler to run.

If we take this example:

```python
# No specified time zone. These will use the local timezone.
schedule.every().day.at("10:30").do(job)
schedule.every().wednesday.at("13:15").do(job)
schedule.every(2).days.at("17:47").do(job)
```

We can enhance it to add one more step to specify the required timezone.

```python
# Defined time zone.
schedule.every().day.at("10:30").tz("America/New_York").do(job)
schedule.every().wednesday.at("13:15").tz("Australia/Sydney").do(job)
schedule.every(2).days.at("17:47").tz("Europe/London").do(job)
```

The benefits of this would be very very helpful. Especially for multi-national companies who need something like this to work at a specified time in a specific timezone.

### PR DESCRIPTION
**Pull request by chrimaho**
Add timezone functionality.

Key changes:
- Adds two new packages to the `__init__.py` file: `pytz` and `tzlocal`.
- Adds a new method: `tz()`
- Adds a new attribute: `at_tz`
- For each of the lines with `datetime.datetime.now()`, it adds the parameter: `tz=self.at_tz`
- Adds docs and tests

Resolves #470.

### CODE REVIEW

**Comment by rudSarkar** [comment]
Hi @SijmenHuizenga,

Near future timezone will add on schedule module? because sometimes VPS/VPC in other countries so it doesn't match the time local need to write extra code to identify the timezone.

Looking forward to hearing from you.

Thanks

**Comment by SijmenHuizenga** [comment]
Hi @rudSarkar and @chrimaho, what do you think of #517? Would that help you out? Looking forward to your thought!

**Comment by chrimaho** [comment]
Hi @dbader and @SijmenHuizenga , I really like this new info within #517 . Especially the optional `pytz` module and lazy-loading for it's import. I think that this will work really well!

I also think that having a separate module will not be necessary. I understand the prerogative for having the core `scheduler` as streamlined and simple as possible. But I also think that having Time Zone functionality is a common functionality and should be part of the base product for this library.

Moreover, it becomes particularly apparent when using this library on a server (eg. on AWS), and when the time-zone of the server (eg. Landing Zone) is not the same local timezone of where the Python app will be used. So, it's I think that having this time-zone functionality here in this one library is important. And the suggestion here by @SijmenHuizenga looks very good 👍

Reading through the code on the PR, I think that it is easy enough to resolve those errors raised by PyTest and MyPy. If you Merge #517 in, I am happy to fix it.

**Comment by samgermain** [comment]
> Hi @dbader and @SijmenHuizenga , I really like this new info within #517 . Especially the optional `pytz` module and lazy-loading for it's import. I think that this will work really well!
> 
> I also think that having a separate module will not be necessary. I understand the prerogative for having the core `scheduler` as streamlined and simple as possible. But I also think that having Time Zone functionality is a common functionality and should be part of the base product for this library.
> 
> Moreover, it becomes particularly apparent when using this library on a server (eg. on AWS), and when the time-zone of the server (eg. Landing Zone) is not the same local timezone of where the Python app will be used. So, it's I think that having this time-zone functionality here in this one library is important. And the suggestion here by @SijmenHuizenga looks very good 👍
> 
> Reading through the code on the PR, I think that it is easy enough to resolve those errors raised by PyTest and MyPy. If you Merge #517 in, I am happy to fix it.

Or at least be able to use UTC

**Comment by rudSarkar** [comment]
Hi, @SijmenHuizenga I think it's fine but there are a few errors on testing, and not possible to merge right away, If the issue will be fixed it can be usable with timezone support.

Added a comment on #517 PR about the optional field of the timezone, It's a good idea to make timezone optional.

**Pull request closed without merging**
